### PR TITLE
feat: change the layout algo

### PR DESCRIPTION
**Pull request by itsnotpolza**
Main difference is instead of looping through all of the possible layouts this one looks at best of two, unfortunately I couldn't bring it down to just one :( 

Also shortened the width getter down to two calculations.

### CODE REVIEW

**Comment by LucasAlda** [comment]
Amazing algo, how did you end up with that way to get the two best cols? nice math

**Comment by LucasAlda** [comment]
I think you can improve the func prop and all that by extracting the sqrt calculation to get the cols and use it only with Math.floor and getting the alternative by adding one

Then the updated getLayout will receive the cols number

**Comment by LucasAlda** [comment]
With that minor change, I'll happily merge

**Comment by itsnotpolza** [comment]
Here are my notes on how i got the formula, didn't notice the question before because timezones
image

**Pull request merged**
